from app.openai_client import generate_structured_brief

result = generate_structured_brief("GENERA UN BRIEF PARA UN EVENTO DE AI EN MEDELLIN")
print(result)
print("---TITLE---")
print(result.title)
print("---OBJECTIVE---")
print(result.objective)
print("---AUDIENCE---")
print(result.audience)
print("---TONE---")
print(result.tone)
print("---CHANNELS---")
print(result.channels)
print("---NEXT STEPS---")
print(result.next_steps)